import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { ASSET_BUCKET, SIGNED_URL_TTL_SECONDS } from "@/lib/storage";
import { signedRenditionUrl, RENDITION_SIZES } from "@/lib/image-url";
import type { CreateProjectInput, ProjectWithCounts } from "@/types";

/**
 * GET /api/projects
 * Returns all non-archived projects for the authenticated team.
 * Auth is enforced by middleware; RLS additionally restricts to
 * authenticated sessions only (team_all policy).
 *
 * Week 7: each project with a `cover_image_path` gets a `cover_image_url`
 * (signed, 1hr TTL) minted here — same pattern as the dashboard server
 * component's direct query — so any consumer of this route (including
 * Aria) sees a ready-to-use image URL rather than having to know to
 * call GET /api/projects/[id]/cover per project.
 */
export async function GET() {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: projects, error } = await supabase
    .from("projects")
    .select("*")
    .order("updated_at", { ascending: false });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  // Phase 14A perf: this list feeds card-style consumers (dashboard-
  // equivalent grids and Aria's API reads), so the cover is signed with
  // an inline resize transform rather than shipping the full-size
  // original — see lib/image-url.ts. Falls back to a plain signed URL
  // if the transform call errors.
  const withCovers: ProjectWithCounts[] = await Promise.all(
    (projects ?? []).map(async (p) => {
      if (!p.cover_image_path) return { ...p, cover_image_url: null };
      const rendition = await signedRenditionUrl(
        supabase,
        ASSET_BUCKET,
        p.cover_image_path,
        SIGNED_URL_TTL_SECONDS,
        { width: RENDITION_SIZES.card }
      );
      if (rendition) return { ...p, cover_image_url: rendition };
      const { data: signed } = await supabase.storage
        .from(ASSET_BUCKET)
        .createSignedUrl(p.cover_image_path, SIGNED_URL_TTL_SECONDS);
      return { ...p, cover_image_url: signed?.signedUrl ?? null };
    })
  );

  return NextResponse.json({ projects: withCovers });
}

/**
 * POST /api/projects
 * body: { name, client_name, address?, monday_board_id?, budget? }
 * Creates a new project. client_token is generated by the database
 * default (gen_random_bytes) — never set from the request body.
 */
export async function POST(request: NextRequest) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: CreateProjectInput;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!body.name?.trim() || !body.client_name?.trim()) {
    return NextResponse.json(
      { error: "name and client_name are required" },
      { status: 400 }
    );
  }

  const { data: project, error } = await supabase
    .from("projects")
    .insert({
      name: body.name.trim(),
      client_name: body.client_name.trim(),
      address: body.address?.trim() || null,
      monday_board_id: body.monday_board_id?.trim() || null,
      budget: body.budget ?? null,
      created_by: user.id,
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ project }, { status: 201 });
}
