import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import type { CreateProjectInput } from "@/types";

/**
 * GET /api/projects
 * Returns all non-archived projects for the authenticated team.
 * Auth is enforced by middleware; RLS additionally restricts to
 * authenticated sessions only (team_all policy).
 */
export async function GET() {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: projects, error } = await supabase
    .from("projects")
    .select("*")
    .order("updated_at", { ascending: false });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ projects });
}

/**
 * POST /api/projects
 * body: { name, client_name, address?, monday_board_id?, budget? }
 * Creates a new project. client_token is generated by the database
 * default (gen_random_bytes) — never set from the request body.
 */
export async function POST(request: NextRequest) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: CreateProjectInput;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!body.name?.trim() || !body.client_name?.trim()) {
    return NextResponse.json(
      { error: "name and client_name are required" },
      { status: 400 }
    );
  }

  const { data: project, error } = await supabase
    .from("projects")
    .insert({
      name: body.name.trim(),
      client_name: body.client_name.trim(),
      address: body.address?.trim() || null,
      monday_board_id: body.monday_board_id?.trim() || null,
      budget: body.budget ?? null,
      created_by: user.id,
    })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ project }, { status: 201 });
}
