name: RESLU
options:
  bundleIdPrefix: au.com.reslu
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
packages:
  WebRTC:
    path: Packages/WebRTC
targets:
  RESLU:
    type: application
    platform: iOS
    sources:
      - path: RESLU
    dependencies:
      - package: WebRTC
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: au.com.reslu.spec
        DEVELOPMENT_TEAM: 3THNC3HJ63
        INFOPLIST_FILE: RESLU/Info.plist
        CODE_SIGN_ENTITLEMENTS: RESLU/RESLU.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: false
    scheme:
      testTargets: []
